### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by Gowixx** [josephworks/YanchopKotlin#4]
Hello there, I was just checking this source, but I don't know how to implement it. I've never implemented anything that's not inside of Autumn **AHEM**, fan client before. Please is there a discord I can contact you for, I have a freecam (Hypixel Fly) that I can give to you for free if we keep this a secret.

-cedo

**Comment by AcaiBerii** [comment]
secret

**Comment by josephworks** [comment]
LMAO very funny
